apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: che-demo
  labels:
    app: che-demo
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      inter.broker.protocol.version: '3.4'
    version: 3.4.0
    storage:
      size: 1Gi
      deleteClaim: true
      type: persistent-claim
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
  zookeeper:
    storage:
      deleteClaim: true
      size: 1Gi
      type: persistent-claim
    replicas: 1